name: Auto PR Commentor
run-name: Adding Comments to PR
on: pull_request
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        
      - name: Check TF Changes
        id: change_check        
        shell: pwsh
        run: |
            if ( $PLAN.Contains("No changes. Your infrastructure matches the configuration.")) {
                echo "No Changes Planned -- Auto merge & Deploy"
            }
            else {
                echo "Changes planned -- Check it!"
            }